name: simcardiac
services:
  cuda_trt:
    image: ghcr.io/npuheart/docker:cuda-trt-v0.0
    # user: "1005:1005"
    volumes:
        - ./log:/var/log
        - ../:/root/DeepHeart
    ports:
      - "2224:22"
    command: /usr/sbin/sshd -D

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]